_target_: src.architectures.huggingface_architecture.HuggingFaceArchitecture

model:
  _target_: src.architectures.models.huggingface_model.HuggingFaceModel
  pretrained_model_name: ${pretrained_model_name}

pretrained_model_name: ${pretrained_model_name}
strategy: ${strategy}
lr: ${lr}
weight_decay: ${weight_decay}
warmup_rate: ${warmup_rate}
eta_min_rate: ${eta_min_rate}
interval: step
