_target_: src.architectures.huggingface_architecture.HuggingFaceArchitecture

model:
  _target_: src.architectures.models.huggingface_model.HuggingFaceModel
  pretrained_model_name: ${pretrained_model_name}

pretrained_model_name: ${pretrained_model_name}
strategy: ${strategy}
lr: ${lr}
weight_decay: ${weight_decay}
warmup_ratio: ${warmup_ratio}
eta_min_ratio: ${eta_min_ratio}
interval: step
